### PR TITLE
Update iOS example to use graphhopper 1.0

### PR DESCRIPTION
**Pull request by OlKir**
Most of the work in this PR has done by @oflebbe. My repository is forked from his https://github.com/oflebbe/graphhopper-ios
If it's incorrect way to make a contribution I'm ready to direct my PR to @oflebbe repository first and wait for his approval.

Main changes from my side:
- [x] Updated iOS code to use graphhopper 1.0 method names
- [x] Point graphhopper submodule to use proper state of `ios_compatibility` branch
- [x] Removed failing architectures from build script
- [x] Changed script that downloads map to retrieve Isle of Man as it's small and it's visually clear where to try directions calculation.
- [x] Updated instruction how to use example

### CODE REVIEW

**Comment by OlafFlebbeBosch** [comment]
Thanks for the credits. I think this PR is correctly placed to this repository.

**Comment by karussell** [comment]
Thanks!

**Comment by ghost** [comment]
It works for me as well!

image

**Comment by ghost** [comment]
Thanks @OlKir for finishing it!

**Comment by karussell** [comment]
Really nice! Thank you @OlafFlebbeBosch & @OlKir !

**Comment by karussell** [comment]
Just tweeted a short "history" summary of this entire project :) 

https://twitter.com/graphhopper/status/1443869754855469056

**Pull request merged**
