### PR TITLE
Changes for modern ios and GraphHopper 1.0

### PR DESCRIPTION
**Pull request by oflebbe**
It just depends on github.com/oflebbe/graphhopper branch ios_compat_new 

Would it be possible as a workaround merge 
github.com/oflebbe/graphhopper branch ios_compat_new  to
github.com/graphhopper/graphhopper branch ios_compat_new (or similary named)
first? 

Since the branch ios-compat is way too old to be resynced to master. 

Open points w/o priorities:
 * Refactor graphhopper to use the master tree only. 
 * Rework build system. It is a bit fragile right now (Or I missed a point).
 * Check memory management.
 * Use the graphhopper YAML config file to autodiscover the Profile needed: The default Profile is hardcoded right now.
 * Don't crash on java exceptions.
 * For Code signing purposes: the original developer team and namespaces have been included.  A script to manage the signing identities might be  needed.

However the patch is included gives value alone, I would propose to handle the open points in subsequent PR's.

### CODE REVIEW

**Comment by karussell** [comment]
There is now a branch with the required changes: https://github.com/graphhopper/graphhopper/commits/ios_compatibility

Do you need anything more from me or should I merge :) ?

**Comment by karussell** [comment]
@oflebbe if you like we can have this easier merged now that we do no longer require a CLA: https://github.com/graphhopper/graphhopper/pull/2279 (the agreement that this contribution stands under the Apache license 2.0 still holds but is implicit due to the project license)

Let me know if I can be of any help to get this merged.

**Comment by oflebbe** [comment]
Please wait a bit longer ... there is progress

**Comment by AF-cgi** [comment]
@oflebbe Any updates?

**Pull request merged**
